# Generated by Django 4.2.23 on 2025-06-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.TextField()),
                ('provincia', models.CharField(max_length=200)),
                ('poblacion', models.CharField(max_length=200)),
                ('pais', models.CharField(max_length=200)),
                ('tarjeta_id', models.CharField(blank=True, max_length=16, null=True, unique=True)),
            ],
        ),
    ]
